#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dataFrameToXts() works", {

  expect_error(
    kwb.base:::dataFrameToXts()
    # argument "dataFrame" is missing, with no default
  )

})

