#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getOverlappingTimeSequences() works", {

  expect_error(
    kwb.base:::getOverlappingTimeSequences()
    # argument "timestamps" is missing, with no default
  )

})

