#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsFilterPeriod() works", {

  expect_error(
    kwb.base:::hsFilterPeriod()
    # argument "tSeries" is missing, with no default
  )

})

