#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("fillup() works", {

  expect_error(
    kwb.base:::fillup()
    # argument "tseries" is missing, with no default
  )

})

