#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsMkTimestamps() works", {

  expect_error(
    kwb.base:::hsMkTimestamps()
    # argument "from" is missing, with no default
  )

})

