#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("selectTimeIntervalDays() works", {

  expect_error(
    kwb.base:::selectTimeIntervalDays()
    # argument "dat" is missing, with no default
  )

})

