#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsFillUp() works", {

  expect_error(
    kwb.base:::hsFillUp()
    # argument "tseries" is missing, with no default
  )

})

