#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsExampleTSeries() works", {

  expect_error(
    kwb.base:::hsExampleTSeries()
    # exactly two of 'to', 'by' and 'length.out' / 'along.with' must be specified
  )

})

