#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotSequenceEvents() works", {

  expect_error(
    kwb.base:::plotSequenceEvents()
    # argument "sequences" is missing, with no default
  )

})

