#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getInterpolatedValues() works", {

  expect_error(
    kwb.base:::.getInterpolatedValues()
    # argument "values" is missing, with no default
  )

})

