#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsST2WT() works", {

  expect_error(
    kwb.base:::hsST2WT()
    # argument "tstamps" is missing, with no default
  )

})

