#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".warnOnNoStepMultiples() works", {

  expect_error(
    kwb.base:::.warnOnNoStepMultiples()
    # argument "timestamps" is missing, with no default
  )

})

