#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsLabValToVal() works", {

  expect_error(
    kwb.base:::hsLabValToVal()
    # argument "x" is missing, with no default
  )

})

