#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("intervalWidthToSeconds() works", {

  expect_error(
    kwb.base:::intervalWidthToSeconds()
    # argument "intervalWidth" is missing, with no default
  )

})

