#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".interpolateAllColumns() works", {

  expect_error(
    kwb.base:::.interpolateAllColumns()
    # argument "tseries" is missing, with no default
  )

})

