#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".stopOnBadArguments() works", {

  expect_error(
    kwb.base:::.stopOnBadArguments()
    # argument "tseries" is missing, with no default
  )

})

