#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".showStartAndEndOfBlock() works", {

  expect_error(
    kwb.base:::.showStartAndEndOfBlock()
    # argument "tbeg" is missing, with no default
  )

})

