#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsPlot() works", {

  expect_error(
    kwb.base:::hsPlot()
    # argument "dev" is missing, with no default
  )

})

