#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsFilterRowsWithValuesInColumns() works", {

  expect_error(
    kwb.base:::hsFilterRowsWithValuesInColumns()
    # argument "columnValuePairs" is missing, with no default
  )

})

