#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsDbTablePlotXY() works", {

  expect_error(
    kwb.base:::hsDbTablePlotXY()
    # argument "strX" is missing, with no default
  )

})

