#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsDelNaRowsOrCols() works", {

  expect_error(
    kwb.base:::hsDelNaRowsOrCols()
    # argument "df" is missing, with no default
  )

})

