#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsGroupBy2Fields() works", {

  expect_error(
    kwb.base:::hsGroupBy2Fields()
    # argument "frmData" is missing, with no default
  )

})

