#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsNiceLabels() works", {

  expect_error(
    kwb.base:::hsNiceLabels()
    # Either labelstep or labelpos must be given.
  )

})

