#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsMfRows() works", {

  expect_error(
    kwb.base:::hsMfRows()
    # argument "nPlots" is missing, with no default
  )

})

