#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".newColumnNames() works", {

  expect_error(
    kwb.base:::.newColumnNames()
    # argument "interpol" is missing, with no default
  )

})

