#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsGroupByInterval() works", {

  expect_error(
    kwb.base:::hsGroupByInterval()
    # argument "data" is missing, with no default
  )

})

