#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getSequenceNumber() works", {

  expect_error(
    kwb.base:::getSequenceNumber()
    # argument "timestamps" is missing, with no default
  )

})

