#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("checkForOverlappingTimeSequences() works", {

  expect_error(
    kwb.base:::checkForOverlappingTimeSequences()
    # object 'checkForOverlappingTimeSequences' not found
  )

})

