#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("selectTimeInterval() works", {

  expect_error(
    kwb.base:::selectTimeInterval()
    # argument "x" is missing, with no default
  )

})

